== Reflexion Dirk Zimmermann
=== Teamrollen: Entwurf/Architekt

In dem Projekt war ich in der ersten Hälfte vor allem im Entwurf tätig und danach fast ausschließlich in der Implementierung. Meine wichtigste Erkenntnis war dabei, dass die Kommunikation das wichtiger als alles andere ist. Damit ist nicht nur die Kommunikation mit den Themenstellern gemeint, sondern vor allem auch innerhalb des Teams. Es gab eine Vielzahl von Problemen, die ich alleine nicht hätte lösen können, die im Team jedoch leicht zu klären waren. Genauso konnte ich auch dabei helfen, Probleme meiner Teammitglieder zu lösen. Zuvor war ich meistens mit meinen Problemen alleingestellt und konnte sie auch selber beherrschen, doch bei einem Projekt dieser Größe war ich gezwungen, sie mit dem Team zu kommunizieren. Das Erklären der Probleme selber hat dabei bereits geholfen, ein besseres Verständnis zu entwickeln.

Nicht zu vernachlässigen sind natürlich auch die technischen Erkenntnisse. Ich habe gelernt, wie man ein komplexes Softwaresystem plant und welche Hilfmittel es dafür gibt. Außerdem wie man eine REST-API aufbaut und wie man mit den begrenzten Ressourcen eines Raspberry Pis umgeht, trotz parallel laufender Prozesse.

Besonders stolz bin ich auf die REST-API. Zu sehen, dass sie nach den langen Überlegungen zum Aufbau und der Umsetzung genau so funktioniert, wie sie soll und erfolgreich Daten übertragen kann, war ein kleines Erfolgserlebnis. Aber ich bin auch stolz auf das Team und das Projekt als ganzes. Auch wenn wir es nicht ganz geschafft haben, alle Anforderungen zu erfüllen, haben wir einen sehr großen Teil davon umsetzen können und konnten dem Kunden ein benutzbares System präsentieren. mit dem dieser zufrieden ist. Das zeigt für mich, dass wir sehr gut zusammengearbeitet haben und die Kommunikation zwischen uns und mit den Kunden insgesamt gut funktioniert hat.

Trotzdem gab es auch Probleme. Ich habe mich während der Construction Phase noch zu sehr mit Dingen aus dem Entwurf aufgehalten. Deshalb wurde die Zeit für mich am Ende für die Implementierung knapp. Auch wenn ich mit meinen Aufgaben fertig wurde, hätte es noch bessere Lösungen gegeben, für die jedoch die Zeit nicht mehr gereicht hat. Dann gab es natülich noch das Problem mit der Verbindung zum Themensteller, das an anderer Stelle bereits erläutert wurde.