==== Alexander Heiß
.Teamrollen: Testing/Management

Bereits im ersten Semester stellte sich für mich heraus, dass ich nicht nur im Bereich des Testings zuständig bin, sondern auch zahlreiche Aufgaben im Projektmanagement mit übernehmen werde. So erstellte ich, wie schon in SE I, auch in diesem Semester die Iterationspläne, erweiterte den Projektplan und aktualisierte das Essence-Modell.

Meiner Hauptaufgabe, dem Testing, konnte ich mich in diesem Semester aber in größerem Umfang widmen. Dafür überlegte ich mir eine Struktur, wie die verschiedenen TestCases sinnvoll und strukturiert tabellarisch dargestellt werden können. Durch diese Überlegungen, den Input aus den Vorlesungen und Praktika sowie weiterem Feedback, lernte ich viel rund um die Tests und konnte mein Vorgehen immer weiter optimieren. Auch festigten sich die Erkenntnisse aus SE I rund um die iterativ inkrementelle Softwareentwicklung und das agile Vorgehen im Allgemeinen. Insbesondere gegen Ende der Projektphase zeigte sich der Vorteil, sich erst auf die wichtigen Elemente zu fokussieren. Aufgrund von zeitlicher Knappheit mussten ein paar Features aus der Software herausgelassen werden.

Dennoch lief nicht alles reibungslos ab: Insbesondere die Kommunikation zum Kunden erwies sich des Öfteren als schwierig und langwierig. Daraus konnte ich den Schluss ziehen, zukünftig früher Wünsche oder Anmerkungen an den Themensteller bzw. Kunden zu senden. Damit kann für alle Beteiligten für eine entspannte Arbeitsatmosphäre gesorgt werden. Auch möchte ich in Folgeprojekten eher mit der Dokumentation des Geschehens anfangen. Das häufig etwas zu späte Anfangen des schriftlichen Teils führt zu einem erhöhten Arbeitsaufwand durch Wiederaufarbeitung der Themen. Zudem werde ich mehr Wert auf einen wohl überlegten Zeitplan setzen, um die Aufgaben zeitlich aufgeteilter erledigen zu können.

Gut funktioniert hat die Aufgabenverteilung im Team. So arbeitete jeder in ähnlicher Auslastung an verschiedenen Fachbereichen und unterstützte, wo Hilfe benötigt wurde. Auch die Kommunikation innerhalb des Teams lief geordnet und zügig ab. Alle Teammitglieder zeigten eine hohe Zuverlässigkeit und ordentliches Arbeiten.

Sehr gut gefallen hat mir das praxisbezogene Lernen. So werden die theoretischen Bestandteile des Semesters deutlich und anwendbar. Auch das gute Ergebnis des Projekts zu sehen, ist ein schönes Gefühl. Unterstrichen wir dies durch die tatsächliche Anwendbarkeit der Soft- sowie Hardware durch die Themensteller und des gesamten Vereins. Auch im Bereich des Managements kann ich vieles in andere Bereiche des Lebens übernehmen. Dabei möchte ich vor allem die Work Item List sowie die Risk List hervorheben, die auch bei anderen Projekten von großem Nutzen sein können.

Zusammenfassend kann ich nur die zahlreichen Erkenntnisse aus Dokumentation, Testing und Teamarbeit positiv hervorheben. Das Gelernte kann definitiv im weiteren Studienverlauf, insbesondere im folgenden Praxisprojekt, und im Arbeitsalltag in großem Umfang angewendet werden.
