= 1.Projektplanung


=== 1.1 - Aufgabenstellung & Auftraggeber 

Im Rahmen unserer studentischen Projektarbeit im Modul "Software Engineering" hat uns der Verein "Mfc-Rossendorf" die Möglichkeit gegeben, eine Anwesenheitserfassung des Modellflugplatzes zu entwickeln. 
Das System soll es dem "Vereinsflugplatz des Mfc-Rossendorf" in Zukunft erlauben, eine digitalisierte Anwesenheitserfassung/Protokollierung der Piloten zu nutzen, um damit eine nachvollziehbare und kontrollierte Übersicht über den Praxisbetrieb des Vereinsflugplatzes gewährleisten zu können.

Um einen kontrollierten Betrieb des Vereinsflugplatzes zu gewährleisten, gibt es einige gesetzlich festgelegte bürokratische Maßnahmen zu beachten. Eine davon ist die Erfassung/Protokollierung der anwesenden Piloten. Aktuell wird der Vorgang analog über ein zentrales Flugbuch geregelt, in welches sich beim Betreten und Verlassen eingetragen werden muss. Diese Protokollierung ist notwendig, um abgesichert zu sein und die Nachvollziehbarkeit im Schadensfall oder bei möglichen Beschwerden über Lärm oder Sachschädigung zu gewährleisten.

In Zukunft sollen sich also die Piloten lokal mittels RFID-Ausweis an einem autarken Terminal anmelden bzw. abmelden können. Die An-/Abmeldedaten sollen dabei korrekt erfasst und gesichert werden und über einen Webserver leicht einsehbar und verwaltbar sein. So soll ein digitales System entstehen, welches frei von Unsicherheiten und bürokratischem Aufwand ist.

Bei dem Projekt begleiteten uns auf der einen Seite die wöchentlichen Vorlesungen von Professor Anke und Herrn Zirkelbach als Mentor des Teams, und auf der anderen Seite zwei direkte Ansprechpartner des Vereins "Mfc-Rossendorf". 
*Herr Thomas Brenner* ist Vorsitzender des Vereins Mfc-Rossendorf und setzt deren Ziele, thematische besondere Schwerpunkte und liefert uns die benötigte Hard-/Software. 
Zusätzlich wird, unter anderem, Herr Brenner das System in Zukunft verwalten.
*Herr Prof. Dr. Heino Iwe* ist ebenfalls unser Ansprechpartner. Als langjähriges Mitglied des Vereins Mfc-Rossendorf gibt er uns einen tiefen Einblick in das aktuelle bestehende System und deren Nachteile und überwacht ebenfalls den Projektfortschritt.
Beide Themensteller sind im ständigen Austausch mit Team "E2". Da beide Ansprechpartner im vorherigen Jahr bereits eine studentischen Projektarbeit betreuten, war ihnen das Vorgehen bereits bekannt. 

=== 1.2 - Situation zum Semesterbeginn 

Zu Beginn des Moduls SE 2 hatten wir einen umfassenden Überblick in das System und die nötigen funktionalen Anforderungen gewonnen. (Verweis auf 1. Semester-Iteration)
Da einige Mitglieder aus dem Studiengang Wirtschaftsingenieurwesen (W72) nur im Rahmen eines Ergänzungsmoduls Teil des Projekts waren, wurde unsere Gruppe nach Ablauf des ersten Semesters kleiner. Dadurch veränderten sich die Rollen in unser Gruppe und mussten deshalb in einem der ersten Meetings des zweiten Semesters neu verteilt werden. 
Unter anderen wurde Simon Herbstrith durch Lenny Reitz vom Posten des Teamleiters abgelöst, und Tsatsralterdene Batchimeg verließ das Team der Analyse.
//Gespräch mit Professor Anke -> extra Iteration oder hier ausführen?
//Verweis auf Iteration 

===  1.3 - Team & Rollen

Unser Team umfasst, durch die oben beschriebene Verkleinerung der Gruppe (Verweis auf Situation zum Semesterbeginn), 6 Mitgliedern. Die Ansprechpartner des Vereins "Mfc-Rossendorf" und Herrn Zirkelbach blieben unverändert.
Da in dem zweiten Semester der Fokus nicht mehr ausschließlich auf der theoretischen Analyse lag, haben wir beschlossen, die Teammitglieder der Gruppe Analyse zur Unterstützung mit auf andere Rollen zu verteilen.    
So übernahm Richard Kleint die zusätzlich neu hinzugekommende Rolle Deployment und Jakob Laufer unterstützte Alexander Heiß in der Rolle des Testers. Außerdem übernahm Alexander Heiß den Entwurf der Weboberfläche und andere Entwurfsaufgaben. Für technischere Entwurfsdetails und die Entwicklung waren Max Haufe, Dirk Zimmermann und Lenny Reitz verantwortlich. 
Lenny Reitz leitete das Team, wobei Alexander Heiß unterstützend die Projektorganisation übernahm.

|===

|*Rolle*|*Name*

|Teamleiter
a|* Lenny Reitz

|Projektorganisation
a|* Alexander Heiß

|Analyse
a|* Jakob Laufer
* Richard Kleint

|Entwurf - Technisch
a|* Max Haufe
* Dirk Zimmermann 
* Lenny Reitz

|Entwurf - Weboberfläche, Fachlicher Entwurf  
a|* Alexander Heiß

|Entwicklung
a|* Max Haufe
* Dirk Zimmermann 
* Lenny Reitz

|Test
a|* Alexander Heiß
* Jakob Laufer

|Deployment
a|* Richard Kleint

|===


=== 1.3 - Kommunikation & eingesetzte Tools

Anders als im vergangenen Semester gab es in SE 2 einen vorgegebenen Terminfür Meetings, welcher im Stundenplan festgelegt wurde. 
Da dieser Zeitpunkt für jedes Teammitglied passte, wurde mittwochs, 17 Uhr zu unseren wöchentlichen Termin für Gruppenmeetings.
Obwohl wir uns auch im letzten Semester regelmäßig getroffen haben, gab uns der feste Termin eine gewisse Struktur. 
Als Tool für die Kommunikation nutzten wir den Onlinedienst Discord und für alle weiteren alltäglichen Nachrichten bzw. Informationen WhatsApp. 
Abgesehen von den wöchentlichen Gruppenmeetings trafen wir uns öfters innerhalb der Rollen wieder, um in einem kleineren Kreis auf spezifische Themen näher einzugehen.

Meetings mit den Kunden fanden zu Beginn des Semesters in der Regel alle 2 Wochen statt, bei denen über Google Meet Vorstellungen und Fragen geteilt bzw. geklärt wurden.
Im Laufe des Semesters vergrößerten sich die Abstände der Kundenmeetings und es wurde sich nur noch bei größeren Fortschritten getroffen. Manchmal kam es auch vor, dass wir den Kunden zu unserem wöchentlichen Meeting am Mittwoch eingeladen haben, an dem wir dann ein kurzes Update geben konnten. 
Bei dringenden und kurzen Fragen oder Benachrichtigungen kommunizierten wir per Mail. 



=== 1.4 - Dokumentation & eingesetzte Tools

Für die Dokumentation übernahmen wir die vorgefertigte Ordnerstrukur aus dem vergangenen Semester und führten diese weiter. Wir erweiterten sie, indem wir zusätzliche Verzeichnisse wie Deployment, Test oder Projektbericht einführten. 
Obwohl es bei einigen Dokumenten bei der Formatierung Probleme gab, empfanden wir AsciiDoc als ideales Dokumentationsformat. Einschließlich nutzten wir AsciiDoc -PDF und AsciiDoc -Diagramm für die Konvertierung ins PDF-Format. 
Als Entwicklungsumgebung wurde Visual Studio Code genutzt.
Für Diagramme, Übersichten und Wireframes nutzten wir zusätzlich Tools wie VisualParadigm, PUML, Draw.io und Adobe Photoshop.

Für die einheitliche Strukturierung entwickelten wir Templates bzw. Vorlagen für bestimmte Teile in unserer Dokumentation. 
So konnten wir unter anderen im Projektmanagment die Iterationspläne einheitlich gestalten und hatten bei den Test-Cases, ähnlich wie bei den Use-Cases, ein einheitliches Format. 
//Verweis bzw. Ausschnitt von Templates
Dadurch ging die Bearbeitung oft schneller, da man einen vorgefertigten Rahmen hatte, den man beispielsweise in der jeweiligen Iteration nur noch anpassen musste. Allgemein war die Dokumentation dadurch deutlich besser organisiert und einfacher zu erfassen.

Die Ablaufpläne und Protokolle aus Gruppenmeetings oder Kundenmeetings bereiteten wir mittels Microsoft OneNote vor. Danach haben wir es in unsere Ascii-Dokumentation überführt, damit sie an dieser Stelle vollständig ist. 
Wir haben Microsoft OneNote für Ablaufpläne und Protokolle verwendet, da wir in Kundenmeetings meist den Bildschirm geteilt haben und die Ansicht von Microsoft OneNote präsentierbarer empfanden, als eine halbe PDF Vorschau in Visual Studio Code.

Als Tool der Planung, Verteilung und Iterierung von Aufgaben nutzten wir GitHub Issues. Obwohl das Tool zu Beginn nicht allen bekannt war, gehörte es am Ende zu den wichtigsten Werkzeugen. 
In Gruppenmeetings wurden notwendige Issues gemeinsam erstellt und zugeteilt, geschlossene Issues besprochen und der Fortschritt wurde im Iterationsplan notiert. Dieser Vorgang wurde routiniert wöchentlich durchlaufen.  

//Programm für Fortschritt (Essence Navigator) -> nutzen wir nicht mehr 

=== 1.5 - Way of Working?

//extra Absatz?















