= 1.Projektplanung


=== 1.1 - Aufgabenstellung & Auftraggeber 

Im Rahmen unserer studentischen Projektarbeit im Modul "Software Engineering" hat uns der Verein "Mfc-Rossendorf" die Möglichkeit gegeben, eine Anwesenheitserfassung des Modellflugplatzes zu entwickeln. 
Das System soll es dem "Vereinsflugplatz des Mfc-Rossendorf" in Zukunft erlauben, eine digitalisierte Anwesenheitserfassung/Protokollierung der Piloten zu nutzen, um damit eine nachvollziehbare und kontrollierte Übersicht über den Praxisbetrieb des Vereinsflugplatzes gewährleisten zu können.

Um einen kontrollierten Betrieb des Vereinsflugplatzes zu gewährleisten, gibt es einige gesetzlich festgelegte bürokratische Maßnahmen zu beachten. Eine davon ist die Erfassung/Protokollierung der anwesenden Piloten. Aktuell wird der Vorgang analog über ein zentrales Flugbuch geregelt, in welches sich beim Betreten und Verlassen eingetragen werden muss. Diese Protokollierung ist notwendig, um abgesichert zu sein und die Nachvollziehbarkeit im Fall eines Schadens oder bei möglichen Beschwerden über Lärm oder Sachschädigung zu gewährleisten.

In Zukunft sollen sich also die Piloten lokal mittels RFID-Ausweis an einem autarken Terminal anmelden bzw. abmelden können. Die An-/Abmeldedaten sollen dabei korrekt erfasst und gesichert werden und über einen Webserver leicht einsehbar und verwaltbar sein. So soll ein digitales System entstehen, welches frei von Unsicherheiten und bürokratischem Aufwand ist.

Bei dem Projekt begleiteten uns auf der einen Seite die wöchentlichen Vorlesungen von Professor Anke und Herrn Zirkelbach als Mentor des Teams, und auf der anderen Seite zwei direkte Ansprechpartner des Vereins "Mfc-Rossendorf". 
*Herr Thomas Brenner* ist Vorsitzender des Vereins Mfc-Rossendorf und setzt deren Ziele, thematische besondere Schwerpunkte und liefert uns die benötigte Hard-/Software. 
Zusätzlich wird, unter anderem, Herr Brenner das System in Zukunft verwalten.
*Herr Professor Heino Iwe* ist ebenfalls unser Ansprechpartner. Als langjähriges Mitglied des Vereins Mfc-Rossendorf gibt er uns einen tiefen Einblick in das aktuelle bestehende System und deren Nachteile und überwacht ebenfalls den Projektfortschritt.
Beide überwachen den Projektfortschritt und sind im ständigen Austausch mit Team "E2". Da beide Ansprechpartner im vorherigen Jahr bereits eine studentischen Projektarbeit betreuten, war ihnen das Vorgehen bereits bekannt. 

=== 1.2 - Situation zum Semesterbeginn 

Zu Beginn des Moduls SE 2 hatten wir einen umfassenden Überblick in das System und die nötigen funktionalen Anforderungen gewonnen. (Verweis auf 1. Semester-Iteration)
Da einige Mitglieder aus dem Studiengang Wirtschaftsingenieurwesen (W72) nur im Rahmen eines Ergänzungsmoduls Teil des Projektes waren, wurde unsere Gruppe nach Ablauf des ersten Semesters kleiner. Dadurch veränderten sich die Rollen in unser Gruppe und mussten deshalb in einem der ersten Meetings des zweiten Semesters neu verteilt werden. 
Unter anderen wurde Simon Herbstrith durch Lenny Reitz vom Posten des Teamleiters abgelöst, und Tsatsralterdene Batchimeg verließ das Team der Analyse.
//Gespräch mit Professor Anke -> extra Iteration oder hier ausführen?
//Verweis auf Iteration 

===  1.3 - Team & Rollen

Abgesehen von der oben beschriebene verkleinerung der Gruppe (Verweis auf Situation zum Semesterbeginn) blieb unsere Gruppe von 6 Mitgliedern gleich. Auch die Ansprechpartner des Vereins "Mfc-Rossendorf" und Herrn Zirkelbach als Mentor blieben gleich.
Da in dem zweiten Semester der Fokus nicht mehr ausschließlich auf der theoretischen Analyse lag, haben wir beschlossen, die Teammitglieder der Gruppe Analyse zur Unterstützung mit auf andere Rollen zu verteilen.    
So übernahm Richard Kleint die zusätzlich neu hinzugekommende Rolle Deployment und Jakob Laufer sollte Alexander Heiß in der Rolle des Testers unterstützen. Neben der Rolle des Testers übernahm Alexander Heiß das Webdesign welches ein Teilgebiet des Entwurfs ist. Auf der anderen Seite des Entwurfs waren Max Haufe, Dirk Zimmermann und Lenny Reitz für den eher technischen Aspekt verantwortlich. 
Für den Bereich der technischen Umsetzung, der Implementierung, waren ebenfalls Max Haufe, Dirk Zimmermann und Lenny Reitz verantwortlich.
Wie bereits erwähnt wurde Lenny Reitz unser neuer Teamleiter, wobei Alexander Heiß unterstützend die Projektorganisation übernahm.

|===

|*Rolle*|*Name*

|Teamleiter
a|* Lenny Reitz

|Projektorganisation
a|* Alexander Heiß

|Analyse
a|* Jakob Laufer
* Richard Kleint

|Entwurf - Technisch 
a|* Max Haufe
* Dirk Zimmermann 
* Lenny Reitz

|Entwurf - Webdesign  
a|* Alexander Heiß

|Implementierung
a|* Max Haufe
* Dirk Zimmermann 
* Lenny Reitz

|Test
a|* Alexander Heiß
* Jakob Laufer

|Deployment
a|* Richard Kleint

|===


=== 1.3 - Kommunikation & eingesetzte Tools

Anders als im vergangenen Semester gab es in SE 2 ein möglichen Termin, welcher im Stundenplan festgelegt wurde. 
Da jeder aus unserer Gruppe zu diesem Zeitpunkt konnte, wurde der Mittwoch um 17 Uhr zu unseren wöchentlichen Tag für Gruppenmeetings.
Obwohl wir uns auch im letzten Semester regelmäßig getroffen haben, gab uns der feste Termin eine gewisse Struktur. 
Als Tool für die Kommunikation nutzten wir den Onlinedienst Discord und für alle weiteren altäglichen Nachrichten bzw. Informationen WhatsApp. 
Abgesehen von den wöchentlichen Gruppenmeetings trafen wir uns des öfteren innerhalb der Rollen wieder, um in einem kleineren Kreis auf spezifische Themen näher einzugehen.

Meetings mit den Kunden fanden zu Beginn des Semesters in der Regel alle 2 Wochen statt, bei denen über GoogleMeets Vorstellungen und Fragen geteilt bzw. geklärt wurden.
Im laufe des Semestern vergrößerten sich die Abstände der Kundenmeetings und es wurde sich nur noch bei größeren Fortschritten getroffen. Manchmal kam es auch vor, dass wir den Kunden zu unserem wöchentlichen Mittwochsmeeting eingeladen haben, wo wir ein kurzes Update geben konnten. 
Bei dringenden und kurzen Fragen oder Benachrichtigungen kommunizierte man per E-Mail miteinander. 



=== 1.4 - Dokumentation & eingesetzte Tools

Für die Dokumentation übernahmen wir die vorgefertigte Ordnerstrukur aus dem vergangenen Semester und führten diese weiter. Wir erweiterten diesen, indem wir zusätzliche Folder wie Deployment, Test oder Projektbericht hinzufügten. 
Obwohl es bei einigen bei der Formatierung Probleme gab, empfanden wir AsciiDoc als ideales Dokumentationsformat. Einschließlich nutzten wir AsciiDoc -PDF und AsciiDoc -Diagramm für die Konvertierungen. 
Als Entwicklungsumbegung nutzten wir Visual Studio Code.
Für die Diagramme, Übersichten und Wireframes nutzten wir zusätzlich Tools wie Puml, Draw.io und Photoshop. Gründe dafür waren hauptächlich, das uns die Tools bekannt waren und wir Erfahrung in dessen Bedienung hatten.

Für die einheitliche Strukturierung entwickelten wir Templates bzw. Vorlagen für bestimmte Teile in unserer Dokumentation. 
So konnten wir unter anderen im Projekt Managment die Iterationspläne einheitlich gestalten und hatten bei den Test-Cases, ähnlich wie bei den Use-Cases, ein einheitliches Format. 
//Verweis bzw. Ausschnitt von Templates
Dadurch ging die Bearbeitung oft schneller, da man einen vorgefertigten Rahmen hatte, den man beispielsweise der jeweiligen Iteration nur Anpassen musste. 
Allgemein war die Dokumentation dadurch deutlich besser organisiert und einfacher zu erfassen.

Die Ablaufpläne und Protokollierungen aus Gruppenmeetings oder Kundenmeetings bereiteten wir mittels Microsoft OneNote vor bzw. nach. Danach haben wir es in unsere Ascii-Dokumentation überführt, damit es an dieser stelle vollständig ist. 
Warum wir es erst in Microsoft OneNote notiert haben und nicht gleich in Ascii-Doc, ist aus Gründen der Form entstanden. Da wir den Ablaufplan meist mit dem Kunde teilten, empfanden wir die äußere Ansicht von Microsoft OneNote deutlich besser als eine halbe PDF Vorschau in Visual Studio Code. 

Als Tool der Planung, Verteilung und Iterierung von Aufgaben nutzten wir GitHub Issues. Obwohl das Tool zu Beginn nicht allen bekannt war, gehörte es am Ende zu den wichtigsten Tools. 
In Gruppenmeetings wurden notwendige Issues gemeinsam erstellt und zugeteilt, und geschlossene Issues wurden besprochen und der Fortschritt wurde im Iterationsplan notiert. Das war ein Vorgang der routiniert wöchentlich durchlaufen wurde.  

//Programm für Fortschritt (Essence Navigator) -> nutzen wir nicht mehr 

=== 1.5 - Way of Working?

//extra Absatz?















