= Planung (ca. 4 Seiten)

Im Rahmen unserer studentischen Projektarbeit im Modul "Software Engineering" hat uns der Verein "Mfc-Rossendorf" die Möglichkeit gegeben, eine Anwesenheitserfassung des Modellflugplatzes zu entwickeln. 
Das System soll es dem "Vereinsflugplatz des Mfc-Rossendorf" in Zukunft erlauben, eine digitalisierte Anwesenheitserfassung/Protokollierung der Piloten zu nutzen, um damit eine nachvollziehbare und kontrollierte Übersicht über den Praxisbetrieb des Vereinsflugplatzes gewährleisten zu können.

Um einen kontrollierten Betrieb des Vereinsflugplatzes zu gewährleisten, gibt es einige gesetzlich festgelegte bürokratische Maßnahmen zu beachten. Eine davon ist die Erfassung/Protokollierung der anwesenden Piloten. Aktuell wird der Vorgang analog über ein zentrales Flugbuch geregelt, in welches sich beim Betreten und Verlassen eingetragen werden muss. Diese Protokollierung ist notwendig, um abgesichert zu sein und die Nachvollziehbarkeit im Fall eines Schadens oder bei möglichen Beschwerden über Lärm oder Sachschädigung zu gewährleisten.

In Zukunft sollen sich also die Piloten lokal mittels RFID-Ausweis an einem autarken Terminal anmelden bzw. abmelden können. Die An-/Abmeldedaten sollen dabei korrekt erfasst und gesichert werden und über einen Webserver leicht einsehbar und verwaltbar sein. So soll ein digitales System entstehen, welches frei von Unsicherheiten und bürokratischem Aufwand ist.

Bei dem Projekt begleiteten uns auf der einen Seite die wöchentlichen Vorlesungen von Professor Anke und Herrn Zirkelbach als Mentor des Teams, und auf der anderen Seite zwei direkte Ansprechpartner des Vereins "Mfc-Rossendorf". 
*Herr Thomas Brenner* ist Vorsitzender des Vereins Mfc-Rossendorf und setzt deren Ziele, thematische besondere Schwerpunkte und liefert uns die benötigte Hard-/Software. 
Zusätzlich wird, unter anderem, Herr Brenner das System in Zukunft verwalten.
*Herr Professor Heino Iwe* ist ebenfalls unser Ansprechpartner. Als langjähriges Mitglied des Vereins Mfc-Rossendorf gibt er uns einen tiefen Einblick in das aktuelle bestehende System und deren Nachteile und überwacht ebenfalls den Projektfortschritt.
Beide überwachen den Projektfortschritt und sind im ständigen Austausch mit Team "E2". Da beide Ansprechpartner im vorherigen Jahr bereits eine studentischen Projektarbeit betreuten, war ihnen das Vorgehen bereits bekannt. 

Das Team "E2" wurde auf Grundlage eines Fragebogens von Professor Anke zusammengestellt. Dabei wurde auf Interessen und Vorkenntnisse Rücksicht genommen. 

* 1 Semester Rollen:
* Projektmanagement: Simon
* Analyse: Jakob, Richard, Tsatsra
* Entwurf: Technisch: Max, Dirk, Lenny; Webdesign: Alexander
* Implementierung: Max, Dirk, Lenny
* Test: Alexander

* 2 Semester Rollen:
* Projektmanagement: Lenny
* Analyse: Jakob, Richard
* Entwurf: Technisch: Max, Dirk, Lenny; Webdesign: Alexander
* Implementierung: Max, Dirk, Lenny
* Test: Alexander, Jakob
* Deployment: Richard


* Kommunikation 
--> im gesamten Team 1 pro Woche --> in Rollengruppen zusätzlich 1 pro Woche 
--> Kundenmeeting ca. alle 2 Wochen
--> Discord, whatsApp, Google Meet, Email, Fragen bei Praktika in BBB

* Dokumetation eingestzte Techniken 
--> Tools wie Ascii, vorgefertige Ordnerstruktur
--> Draw.io 
--> Photoshop
--> Puml
--> Programm für Fortschritt (Essence Navigator)


