= Meetingplan für den 14.01.2021
1.0, 14.01.2021
:toc: 
:toc-title: Inhaltsverzeichnis

== Ablauf

* Use-Cases mit Wireframes vorstellen
** Lenny zeigt Use-Case-Übersicht & Wireframes per Bildschirmübertragung
** Beginn: Login, Startseite, Startseite-Admin von Alex vorgestellt 
** Jeder stellt seinen eigenen Use-Case vor (nur sprachlich während Übersicht gezeigt wird) und stellt evtl. vorhandene Fragen

* Tastenkombinationen vorstellen (Lenny)

* Erweiterete Systemübersicht zeigen (Lenny)

== Fragen:
* Wie wird das System übergeben? Implemtieren wir das auf einem laufenden Server?
** Wenn ja: Wird der Server aktuell verwendet oder kann als Testserver fungieren?
** Welches Betriebssystem läuft auf dem Server?
* Besteht schon eine Domain für die Website?
* Welcher Raspi wird verwendet?
* Wird uns der Raspi übergeben? Direkt zum Start des 2. Semesters
* Welche RGB-Lampe? Wie viele Farben möglich?
* Können Admins eine Aktualisierung des Systems anfordern? (aktuelles Protokoll wird synchronisiert)
* Meinung zu Vorgang Piloten abmelden am Raspi



== Pläne bzw. Fragen an Herrn Zirkelbach:

* (Testfälle entwerfen)
* "Grundkonzept der Architektur"
** Domänenmodell?
** Datenbankmodell?

=== Vorschläge
Der Akteur ist lediglich derjenige, der sich mit dem Usecase beschäftigt (siehe Usecasemodell)

Usecasemodell: Include Beziehung UC02-UC06 und UC01->UC07 entfernen. Vereinsmitglied -> UC06
Extend UC07->UC01 und Vereinsmitglied ->UC07

Aus Usecasemodell Verwaltung und Protokoll entfernen


== Erkenntnisse
==== Usecases
UC1: Vorbedingung: Vereinsmitglied ist nicht angemeldet

UC04: Nutzer können lediglich deaktiviert werden. Möglichkeit der Reaktivierung soll gegeben sein. Hier muss erneut ein RFID Tag vergeben werden

UC06: 

-Automatisches Abmelden um 24 Uhr (Abmeldezeit nicht 00:00 sondern Kenntlichmachung „Automatische Abmeldung“) Es darf nicht im dunkeln geflogen werden. (Akteur: Zeitlicher Trigger)

-Abmeldung über die Website im Adminbereich

-Abmeldung manuell über Taster

Der Usecase soll einfach modifiziert werden können (Über Adminbereich) Beispielsweise Änderung der Zeit der automatischen Abmeldung.

UC08: Info auf Website: Letzter Datenabgleich: xx:xx 
Bei Fehlerfall Info an Admin: „Seit 30 min keine Verbindung mehr!“
Suche und Filtern nach Datumsbereich einbinden

==== Allgemeine Änderungen bzgl. Glossary: 
Begrifflichkeiten (Flugzeiten, Zeiten, Anmeldedaten…) einheitlich machen. Der Gesetzgerber gibt die Begrifflichkeit „Flugbuch“ vor.


==== Ergänzungen zu nicht funktionalen Anforderungen: 
-Anfallende Daten werden bei bestehender Internetverbindung synchronisiert. 

-Bei Störungen Administrator benachrichtigen: „Seit 30 min keine Verbindung mehr!“

-Berechtigung der Protokolleinsicht: Jedes Vereinsmitglied darf Protokolldaten sehen


== Offene Fragen

Umgang mit Gastflügen wird noch mit den Themenstellern geklärt.


