= Meetingplan für den 14.01.2021
1.0, 14.01.2021
:toc: 
:toc-title: Inhaltsverzeichnis

== Ablauf

* Use-Cases mit Wireframes vorstellen
** Lenny zeigt Use-Case-Übersicht & Wireframes per Bildschirmübertragung
** Beginn: Login, Startseite, Startseite-Admin von Alex vorgestellt 
** Jeder stellt seinen eigenen Use-Case vor (nur sprachlich während Übersicht gezeigt wird) und stellt evtl. vorhandene Fragen

* Tastenkombinationen vorstellen (Lenny)

* Erweiterete Systemübersicht zeigen (Lenny)

== Fragen:
* Wie wird das System übergeben? Implemtieren wir das auf einem laufenden Server?
** Wenn ja: Wird der Server aktuell verwendet oder kann als Testserver fungieren?
** Welches Betriebssystem läuft auf dem Server?
* Besteht schon eine Domain für die Website?
* Welcher Raspi wird verwendet?
* Wird uns der Raspi übergeben? Direkt zum Start des 2. Semesters
* Welche RGB-Lampe? Wie viele Farben möglich?
* Können Admins eine Aktualisierung des Systems anfordern? (aktuelles Protokoll wird synchronisiert)
* Meinung zu Vorgang Piloten abmelden am Raspi



== Pläne bzw. Fragen an Herrn Zirkelbach:

* (Testfälle entwerfen)
* "Grundkonzept der Architektur"
** Domänenmodell?
** Datenbankmodell?

=== Vorschläge
Der Akteur ist lediglich derjenige, der sich mit dem Usecase beschäftigt (siehe Usecasemodell)

UseCase-Modell:

* Include Beziehung UC02->UC06 und UC01->UC07 entfernen
* Vereinsmitglied, Admin, Zeit-Trigger -> UC06
* Vereinsmitglied -> UC07
* Vereinsmitglied, Admin -> UC08
* Extends UC07->UC01
* Verwaltung & Protokoll entfernen


== Erkenntnisse
==== Usecases
* UC01:
** Vorbedingung: Vereinsmitglied ist nicht angemeldet
** Versehentliche Anmeldung -> Dann direkt Abmeldung danach, wird nicht vom System erfasst (zeitlich festgelegt: < 30s, genaue Zeitdauer noch offen, bzw. konfigurierbar)

* UC04:
** Umbennen bzw. neu anlegen zu: "Piloten deaktivieren/reaktivieren"
** Nutzer können lediglich deaktiviert werden. Bei der Deaktivierung wird der zuvor verwendete RFID-Tag freigegeben. Möglichkeit der Reaktivierung soll gegeben sein. Hier muss erneut ein RFID Tag vergeben werden.

* UC05:
** Bestimmte Daten des Mitglieds bleiben fix beim Anlegen eines neuen Mitglieds

* UC06: 
** Automatisches Abmelden um 24 Uhr (Abmeldezeit nicht 00:00 sondern Kenntlichmachung „Automatische Abmeldung, Null-Value“) Es darf nicht im dunkeln geflogen werden. (Akteur: Zeitlicher Trigger)
** Abmeldung über die Website im Adminbereich
** Abmeldung manuell über Taster

* UC07:
** Bestimmung des Flugleiters ist nicht verpflichtend, sondern auf freiwilliger Basis -> Keine Blockierung des Systems

* UC08:
** Info auf Website: Letzter Datenabgleich: xx:xx Uhr
** Bei Fehlerfall Info an Admin: „Seit 30 min keine Verbindung mehr!“
** Suche und Filtern nach Datumsbereich einbinden

==== Allgemeine Änderungen:
* UseCases:
** reduzieren, nicht zu allem was schreiben (es gibt nicht überall Alternative Abläufe)
** nur auf das spezielle Thema des UseCases beschränken, keine äußeren vom System unabhängigen Sachen einbringen
** nur die Akteure spielen eine Rolle, die auch den UseCase direkt ausführen (siehe UseCase-Diagramm)
* Glossary: Begrifflichkeiten (Flugzeiten, Zeiten, Anmeldedaten…) einheitlich machen. Der Gesetzgeber gibt die Begrifflichkeit „Flugbuch“ vor.


==== Ergänzungen zu nicht funktionalen Anforderungen: 
* Anfallende Daten werden bei bestehender Internetverbindung synchronisiert. 
* Bei Störungen Administrator benachrichtigen: „Seit 30 min keine Verbindung mehr!“
* Berechtigung der Protokolleinsicht: Jedes Vereinsmitglied darf Protokolldaten sehen
* Konfiguration der Dauer von Anmeldung (3s) und Alle Piloten abmelden (10s), etc. in einem Einstellungsbereich (Admin-Zugriff)


== Offene Fragen
* Umgang mit Gastflügen wird noch mit den Themenstellern geklärt.


