@startuml component_diagram_v1

[databaseAccess] ..> [userInterface]
[serverConnection] <..> [databaseAccess]
database "Cache" {
    [SQLite] as db1
}
db1 <.> [databaseAccess] : <<local>>

[userInterface] --> LED
Taste -> [userInterface]
[userInterface] <- Scanner


REST - [Backend]
REST <..> [Frontend]  : <<local>>
database "Piloten/Protokollspeicher" {
    [SQLite] as db2
}
db2 <.> [Backend]  : <<local>>

[serverConnection] <-> REST  : <<http>>

@enduml