@startuml component_diagram

node "Terminal" {
    [database_access] ..> [terminal]
    [server_connection] <..> [database_access]
    database "Cache" as db1 {
    }
    db1 <.> [database_access] : <<local>>
}

[terminal] --> LED
Taste -> [terminal]
[terminal] <- Scanner

node "Webserver" {
    REST <..> [Frontend]
    REST - [Backend]
    database "Piloten/Protokollspeicher" as db2 {
    }
    [Backend] <.> db2  : <<local>>
}

[server_connection] <-> REST  : <<http>>

@enduml