@startuml component_diagram_v2

[databaseAccess] ..> [userInterface]
[serverConnection] <..> [databaseAccess]

[userInterface] --> LED
Taste -> [userInterface]
[userInterface] <- Scanner


REST - [Backend]
REST <..> [Frontend]  : <<local>>


[serverConnection] <-> REST  : <<http>>

@enduml