= System-Wide Requirements: {project-name}
Jakob Laufer <jakob.laufer@htw-dresden.de>; Tsatsralterdene Batchimeg <tsatsralterdene.batchimeg@htw-dresden.de>; Richard Kleint <richard.kleint@htw-dresden.de>; Max Haufe <max.haufe@htw-dresden.de>; Alexander Heiß <alexander.heiß@htw-dresden.de>; Simon Herbstrith <simon.herbstrith@htw-dresden.de>; Lenny Reitz <lenny.reitz@htw-dresden.de>; Dirk Zimmermann <dirk.zimmermann@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt {project-name} spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in separaten Dokumenten festgehalten.

== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

// Tags für Einbindung in Architektur-Notebook

//tag::nfaf1[]
* *NFAF-1*: Zugriffsschutz: Schutz der Datenbank durch Admin-Rechte, Einsicht des Flugprotokolls nur für Admins und Piloten
//end::nfaf1[]

// tag::nfaf2[]
* *NFAF-2*: Datensynchronisierung (ereignisgesteuert): Bsp.: Protokoll- und Pilotendaten werden bei der Anmeldung eines Piloten direkt an den Webserver gesendet
// end::nfaf2[]

* *NFAF-3*: Überwachung der Synchronisation: Der Administrator kann einsehen, wann das Flugprotokoll zuletzt synchronisiert wurde und so Rückschlüsse auf mögliche Kommunikationsprobleme ziehen


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

* *NFAU-1*: Aufgabeneffizienz: Simple und intuitive Kombinationen am Terminal (einfaches Anhalten des RFID-Ausweises zum An- und Abmelden)
** Sc-NRAU-1: 
*** Auslöser: RFID-Ausweis am RFID-Scanner
*** Quelle des Auslösers: Pilot
*** Umgebung: arbeitend
*** Systembestandteil: Raspi, RFID-Scanner, LED
*** Antwort: Leuchten der LED
*** Antwortmetrik: nach festgelegten Statusmeldungen

* *NFAU-2*: Online-Hilfe: Bedeutung der Statusmeldungen der LED als Bedienungsanleitung für Piloten sichtbar machen

// tag::nfau3[]
* *NFAU-3*: Benutzerfreundlichkeit: Verwendung der gleichen Weboberfläche für den Webserver auf Smartphone und Desktop-PC verlangt eine Anpassung der Webseite an die Fenstergröße (responsive).
// end::nfau3[]


=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

// tag::nfar1[]
* *NFAR-1*: Korrektheit: Uhrzeit des Raspis muss genau sein und bei bestehender Internetverbindung synchronisiert werden. (Raspi hält die Uhrzeit nicht lokal)
** Sc-NRAR-1: 
*** Auslöser: bestehende Internetverbindung, interner Timer
*** Quelle des Auslösers: Raspi selbst
*** Umgebung: arbeitend
*** Systembestandteil: Raspi
*** Antwort: Aktualisierung der lokalen Uhrzeit
*** Antwortmetrik: Uhrzeit
// end::nfar1[]


=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

// tag::nfap1[]
* *NFAP-1*: Antwortzeiten: An- und Abmeldung innerhalb 3s, Abmelden aller Piloten in 10s (Konfigurierbare Antwortzeiten durch Admins)
** Sc-NRAP-1: 
*** Auslöser: RFID-Ausweis am RFID-Scanner, Betätigung des Knopfs
*** Quelle des Auslösers: Pilot
*** Umgebung: arbeitend
*** Systembestandteil: Raspi, RFID-Scanner, Knopf
*** Antwort: Aktualisierung des Flugprotokolls
*** Antwortmetrik: An/Abmeldung eines Piloten in 3s oder Abmeldung aller Piloten in 10s
// end::nfap1[]

// tag::nfap2[]
* *NFAP-2*: Durchsatz: Mehrere Piloten müssen sich hintereinander (innerhalb von 30 Sekunden) an- und abmelden können
** Sc-NRAP-2: 
*** Auslöser: RFID-Ausweise am RFID-Scanner
*** Quelle des Auslösers: Piloten
*** Umgebung: arbeitend
*** Systembestandteil: Raspi, RFID-Scanner
*** Antwort: Aktualisierung des Flugprotokolls
*** Antwortmetrik: fehlerfreie An/Abmeldung mehrerer Piloten innerhalb von 30s
// end::nfap2[]


=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.

// tag::nfas1[]
* *NFAS-1*: Anpassbarkeit: Adaptation für die Nutzung in der Werkstatt soll möglich sein
// end::nfas1[]

// tag::nfas2[]
* *NFAS-2*: Konfigurierbarkeit: Konfiguration von Antwortzeiten und Statusmeldungen durch Admins
// end::nfas2[]

== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* *NFA+-1*: Implementierung:
** Auf dem Raspberry Pi ist eine Skriptsprache (Python) zu nutzen
** Oberfläche des Webservers soll mit modernem JS-Framework realisiert werden (Vue)

* *NFA+-2*: Plattform: 
** Raspberry Pi OS (Linux) auf Seite des Raspberry Pi
** Webserver soll sich in bestehende Infrastruktur der Wetterstation eingliedern

* *NFA+-3*: Legal: 
** Es ist eine Open-Source Lizenz zu nutzen

== Datenschutz
Aus Datenschutzgründen wird auf eine gesicherte Verbindung gesetzt. Zudem sind die Protokolldaten und Mitgliederdaten nur nach einem erfolgreichen Login ersichtlich. Außer diesen Bereichen werden vom Themensteller vorerst keine weiteren Anforderungen zum Datenschutz gestellt.
