== Use-Case: UC04: Piloten deaktivieren
===	Kurzbeschreibung
In diesem Use-Case wird der komplette Vorgang zum Deaktivieren eines `Vereinsmitglieds (Pilot)` durch den *Administrator* beschrieben.

===	Kurzbeschreibung der Akteure
==== Vereinsmitglied
Der Akteur "Vereinsmitglied" möchte nicht mehr auf dem Modellflugplatz fliegen.

=== Vorbedingungen
. Das *Vereinsmitglied* muss bereits in der Datenbank vorhanden sein, Use-Case UC03 ist hier die Vorraussetzung.
. Der *Administrator* hat Kenntnis über den `Namen` und die `RFID-Nr` des zu deaktivierenden Piloten.
. Der *Administrator* hat sich auf dem _Webserver_ eingeloggt.

=== Standardablauf (Basic Flow)

. Der Use Case beginnt, wenn der *Administrator* auf der _Admin-Seite_ des _Webservers_ in der _Mitgliederübersicht_ ist.
. Der *Administrator* sucht in der _Mitgliederübersicht_ das zu deaktivierende *Vereinsmitglied* und klickt auf _Deaktivieren_.
. Der *Administrator* bestätigt die Aktion.
. Der _RFID-Ausweis_ wird dem *Administrator* übergeben und deaktiviert.
. Der Use Case ist abgeschlossen, das ehemalige *Vereinsmitglied* muss den Flugplatz nun verlassen und kann diesen bis zur Reaktivierung nicht mehr nutzen.

=== Wesentliche Szenarios

==== Erfolgreiches Deaktivieren der Pilotendaten
. Sc1: Die *Verwaltung* deaktiviert ein `Vereinsmitglied` über den _Webserver_ und das *Vereinsmitglied* übergibt im Anschluss den entsprechenden _RFID-Ausweis_ an den *Administrator*.

===	Nachbedingungen
Bei erfolgreicher Durchführung des Use Case müssen folgende Nachbedingungen erfüllt sein:

* Das (ehemalige) *Vereinsmitglied* besitzt keinen _RFID-Ausweis_, mehr um sich am Flugplatz an- und abmelden zu können
* Die `Pilotendaten` des (ehemaligen) *Vereinsmitglieds* befinden sich noch in der Datenbank, jedoch ist das Mitglied "ausgegraut".

=== Besondere Anforderungen
==== Usability

* Um das versehentliche Deaktivieren eines *Vereinsmitglieds* zu verhinden, sollte es ein Popup (o.ä.) geben, wo der Vorgang bestätigt werden muss.