== Use-Case: UC06: Alle Piloten abmelden
===	Kurzbeschreibung

In diesem Use-Case wird der komplette Vorgang der Abmeldung aller *Piloten* beschrieben.

===	Kurzbeschreibung der Akteure
==== Pilot
Der Akteur Pilot nöchte sich und alle anderen *Piloten* abmelden und den Flugplatz verlassen.

==== Administrator
Der Akteur Administrator möchte alle *Piloten* auf einmal abmelden.

=== Vorbedingungen
. Die *Piloten* sind angemeldet.

=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, wenn ein *Pilot* gehen und alle anderen *Piloten* abmelden möchte.
//sicher?
. Der *Pilot* drückt (z.B.) lange auf den _Flugleiterknopf_.
. Alle *Piloten* werden abgemeldet.
//oder wie auch immer es aussehen soll, wenn niemand mehr angemeldet ist
. Die LED hört auf zu leuchten und alle *Piloten* sind abgemeldet.
. Der Vereinsflugplatz kann verlassen werden.
. Der Use-Case ist abgeschlossen.

=== Alternative Abläufe
==== Deadline
Es ist 24:00 Uhr und es sind noch *Piloten* angemeldet.

. Alle Piloten werden automatisch vom _System_ abgemeldet.
. Die LED hört auf zu leuchten und alle Piloten sind abgemeldet.

==== Admin
Der *Administrator* möchte alle *Piloten* abmelden.

. Der *Administrator* klickt auf der _Adminpage_ auf die Schaltfläche _Alle Piloten Abmelden_.
. Die LED hört auf zu leuchten und alle Piloten sind abgemeldet.

=== Wesentliche Szenarios

==== Erfolgreiche Abmeldung

. Sc1: Alle *Piloten* werden abgemeldet.

===	Nachbedingungen
Das Signallämpchen sollte nicht mehr leuchten und alle *Piloten* sollten abgemeldet sein.


=== Besondere Anforderungen

==== Usability

Der Use Case gehört zu der erweiterten Funktionalität des Systems und muss daher für die meisten Piloten einfach und verständlich sein.