== Use-Case: UC01: Vereinsmitglieder anmelden
===	Kurzbeschreibung

In diesem Use-Case wird der komplette Vorgang der Anmeldung eines *Vereinsmitgliedes* beim Betreten des Flugplatzes beschrieben.

===	Kurzbeschreibung der Akteure
==== Vereinsmitglied
Der Akteur "Vereinsmitglied" möchte den Flugplatz betreten und nutzen.

==== Administrator
Der Akteur "Administrator" verwaltet die entstehenden Daten.

=== Vorbedingungen

// . UC03 ist erfüllt
. *Vereinsmitgliedern* wurde ein _RFID-Ausweis_ zugeordnet
. Jedem *Vereinsmitglied* wurde dieser _RFID-Ausweis_ übergeben
. *Vereinsmitglied* hat beim Antreffen auf den Flugplatz den _RFID-Ausweis_ dabei

=== Standardablauf (Basic Flow)

. Der Use Case beginnt, wenn das *Vereinsmitglied* am Flugplatz eintrifft 
. *Vereinsmitglied* hält seinen _RFID-Ausweis_ 3 Sekunden lang an den _RFID-Reader_
. _RFID-Reader_ prüft, ob *Vereinsmitglied* existiert
. IF *Vereinsmitglied* existiert
.. _Signallämpchen_ leuchtet in Grün auf. 
.. Anmeldung erfolgreich
.. `Daten` werden erfolgreich erfasst und protokolliert
.. Vereinsflugplatz darf betreten und genutzt werden. *Vereinsmitglied* hat [.underline]#S1# durchlaufen.
. ELSE *Vereinsmitglied* existiert nicht
.. _Signallämpchen_ blinkt Rot auf.
.. Anmeldung fehlgeschlagen 
.. `Daten` können nicht protokolliert werden
.. Vereinsflugplatz darf nicht betreten werden. *Vereinsmitglied* hat [.underline]#S3# durchlaufen.
.. Sich bei *Administrator* melden 
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe

==== Systemausfall
Wenn *Vereinsmitglied* im Schritt 2 des Standardablauf sich versucht anzumelden, die Anmeldung aus einer anhaltenden technischen Störung fehlschlägt:

//Frage: Bei Systemausfall-->allternatives Flugbuch?
. *Vereinsmitglied* greift zum ursprünglichen manuellen System zurück 
. *Vereinsmitglied* trägt alle geforderten Daten händisch in das Flugbuch ein 
. *Vereinsmitglied* muss die technische Störung an *Administrator* weiterleiten
. Der Use Case wird im Schritt 4d fortgesetzt.


=== Wesentliche Szenarios

==== Erfolgreiche Anmeldung
. Sc1: *Vereinsmitglied* A. trifft am Flugplatz ein. Er durchläuft [.underline]#S1#. *Vereinsmitglied* A. darf den Flugplatz betreten.

==== Fehlgeschlagene Anmeldung
. Sc2.1: *Person* B. trifft am Flugplatz ein. Er/Sie hält einen fremden _RFID-Ausweis_ an den _RFID-Reader_ und durchläuft [.underline]#S3#. Da B. kein Mitglied des Vereines ist, schlägt die Anmeldung fehl. *Person* B. darf den Flugplatz nicht betreten.


. Sc2.2: *Vereinsmitglied* C. trifft am Flugplatz ein. Er/Sie hält sein/ihr _RFID-Ausweis_ 3 Sekunden an den _RFID-Reader_ und versucht sich anzumelden. Da wegen einer anhaltenden technischen Störung die Anmeldung fehlschlägt und das _Signallämpchen_ gar nicht aufleuchtet, muss sich händisch in das Flugbuch eingetragen werden. Außerdem sollte dem *Administrator* Bescheid gegeben werden, in Hinblick auf die technische Störung. *Vereinsmitglied* C. darf den Flugplatz betreten.

==== Flugleiter 

. Sc3.1: *Vereinsmitglied* D. trifft am Flugplatz ein. Da sich schon 2 Mitglieder auf dem Flugplatz befinden, wird [.underline]#S5# ausgeführt. Verweis auf (UC07: Flugleiter bestimmen)

===	Nachbedingungen

Bei erfolgreicher Durchführung des Use Case müssen folgende Nachbedingungen erfüllt sein:

* _Signallämpchen_: Das _Signallämpchen_ sollte sich bei jeder versuchten Anmeldung (erfolgreich oder nicht erfolgreich):

. davor und danach für eine Sekunde ausshalten. 
. auf ihren korrekten Zustand zurücksetzten.  

* Technische Störung: Falls es zu einer anhaltenden technischen Störung kommt, muss sich der *Administrator* um das Problem kümmern, und die manuell eingetragenen `Anmeldedaten` in die `Datenbank` übertragen. 

=== Besondere Anforderungen

==== Usability

* Der Use Case gehört zu der grundlegenden Funktionalität des _Systems_ und muss daher für jedes *Vereinsmitglied* einfach und verständlich sein.

==== Performance

* Das lesen des _RFID-Readers_ sollte "schnell" gehen.

