@startuml use_case_diagram

left to right direction

actor Vereinsmitglied

actor Administrator

rectangle "Anwesenheitserfassung des Modellflugplatzes" {
  
  rectangle "Raspberry Pi (Flugplatz)"{

  (UC1: Piloten anmelden)
  (UC2: Piloten abmelden)
  (UC6: Alle Piloten abmelden)
  (UC7: Flugleiter bestimmen)

  }
  
  rectangle "Webserver"{

  (UC3: Pilotendaten anlegen)
  (UC4: Pilotendaten löschen)
  (UC5: Pilotendaten modifizieren)
  (UC8: Protokoll einsehen)
  (UC9: Protokolldaten nachträglich einfügen)
  (UC10: Handhabung Gastflüge)
  (UC11: Piloten reaktivieren)
  
  }
}


Vereinsmitglied --> (UC1: Piloten anmelden)
(UC1: Piloten anmelden) <.down. (UC7: Flugleiter bestimmen) : extend

Vereinsmitglied --> (UC2: Piloten abmelden)

Vereinsmitglied --> (UC6: Alle Piloten abmelden)


Administrator --> (UC3: Pilotendaten anlegen) 

Administrator --> (UC4: Pilotendaten löschen) 

Administrator --> (UC5: Pilotendaten modifizieren) 

Administrator --> (UC8: Protokoll einsehen) 

Administrator --> (UC9: Protokolldaten nachträglich einfügen) 

Administrator -->  (UC10: Handhabung Gastflüge)

Administrator --> (UC6: Alle Piloten abmelden)

Administrator --> (UC11: Piloten reaktivieren)


@enduml