== Use-Case: UC02 Pilot abmelden
===	Kurzbeschreibung
In diesem Use-Case wird der komplette Vorgang der Abmeldung eines *Piloten* beim Verlassen des Flugplatzes beschrieben.

===	Kurzbeschreibung der Akteure
==== Pilot
Der Akteur "Pilot" möchte sich abmelden und den Flugplatz verlassen.

=== Vorbedingungen
. Der *Pilot* hat sich bereits am _Terminal_ angemeldet

=== Standardablauf (Basic Flow)

. Der *Pilot* hält seinen _RFID-Ausweis_ an den _RFID-Reader_
. Das _System_ prüft, ob der *Pilot* bereits angemeldet ist
. IF *Pilot* angemeldet
.. IF *Pilot* ist *Flugleiter*
... Das _System_ gibt die Flugleiterrolle frei
.. Die Abmeldung wird erfasst und protokolliert
.. Die _LED_ leuchtet zweimal grün auf (siehe S2)

=== Wesentliche Szenarios

==== Erfolgreiche Abmeldung
. Sc1: *Pilot* A. möchte den Flugplatz verlassen. Er hält seinen _RFID-Tag_ 3 Sekunden an den _RFID-Reader_ und meldet sich erfolgreich ab. Die _LED_ leuchtet zweimal grün auf, die Abmeldung wird erfolgreich erfasst und protokolliert und *Pilot* A. kann den Flugplatz verlassen.


===	Nachbedingungen
Bei erfolgreicher Durchführung des Use Case müssen folgende Nachbedingungen erfüllt sein:

* Die _LED_ sollte nach erfolgreicher Abmeldung dauerhaft leuchten, wenn noch andere *Piloten* angemeldet sind. Hat sich der letzte *Pilot* abgemeldet, soll die _LED_ nicht mehr leuchten.

=== Besondere Anforderungen
==== Usability
* Der Use Case gehört zu der grundlegenden Funktionalität des _Systems_ und muss daher für jeden *Piloten* einfach und verständlich sein.

==== Performance
* Das Lesen des _RFID-Tags_ soll eine bestimme konfigurierbare Zeitdauer betragen (standardmäßig 3 Sekunden)

