== Use-Case: UC01 Piloten anmelden
===	Kurzbeschreibung

In diesem Use-Case wird der komplette Vorgang der Anmeldung eines *Piloten* beim Betreten des Flugplatzes beschrieben.

===	Kurzbeschreibung der Akteure
==== Pilot
Der Akteur "Pilot" möchte den Flugplatz betreten und nutzen.

=== Vorbedingungen

. UC03 ist für den *Piloten* erfüllt
. *Pilot* hat beim Antreffen auf den Flugplatz den _RFID-Ausweis_ dabei
. *Pilot* ist noch nicht angemeldet

=== Standardablauf (Basic Flow) 

. Der *Pilot* hält seinen _RFID-Ausweis_ an den _RFID-Reader_
. _System_ prüft, ob *Pilot* existiert
. IF *Pilot* existiert
.. Anmeldung wird erfasst und protokolliert.
.. _LED_ leuchtet grün auf (siehe S1). 
. ELSE *Pilot* existiert nicht
.. _LED_ blinkt rot auf. 


=== Wesentliche Szenarios

==== Erfolgreiche Anmeldung
. Sc1: *Pilot* A. trifft am Flugplatz ein. A. hällt seinen _RFID-Ausweis_ an den _RFID-Reader_. Die Anmeldung wurde erfasst und protokolliert und die _LED_ leuchtet grün auf. A. darf den Flugplatz betreten.

//Systemausfall -> ist für uns nicht relevant (Aussage vom Verein)  

//Nichtfunktionale Anforderung -> Anmeldedaten müssen lokal vorbehalten werden und werden beim späteren Versuch synchronisiert


===	Nachbedingungen

Bei erfolgreicher Durchführung des Use Case müssen folgende Nachbedingungen erfüllt sein:

* Die Anmeldung des *Piloten* ist lokal am _Terminal_ protokolliert. (Eine Synchronsierung des Protokolls erfolgt zu einem späterem Zeitpunkt.)

* Die _LED_ sollte sich bei jeder versuchten Anmeldung (erfolgreich oder nicht erfolgreich):

. davor und danach für eine Sekunde ausschalten. 
. auf ihren korrekten Zustand zurücksetzten.  

//nicht funktionale Anforderungen -> technische Störung -> Admin bescheud geben etc.

=== Besondere Anforderungen
==== Usability
* Der Use Case gehört zu der grundlegenden Funktionalität des _Systems_ und muss daher für jeden *Piloten* einfach und verständlich sein.

==== Performance
* Das Lesen des _RFID-Tags_ soll eine bestimme konfigurierbare Zeitdauer betragen (standardmäßig 3 Sekunden)
