== Use-Case: UC01 Piloten anmelden
===	Kurzbeschreibung

In diesem Use-Case wird der komplette Vorgang der Anmeldung eines *Piloten* beim Betreten des Flugplatzes beschrieben.

===	Kurzbeschreibung der Akteure
==== Pilot
Der Akteur "Pilot" möchte den Flugplatz betreten und nutzen.

=== Vorbedingungen

. UC03 ist erfüllt
. *Pilot* hat beim Antreffen auf den Flugplatz den _RFID-Ausweis_ dabei
. *Pilot* ist noch nicht angemeldet

=== Standardablauf (Basic Flow) 

. Der Use Case beginnt, wenn der *Pilot* seinen _RFID-Ausweis_ an den _RFID-Reader_ hält
. _RFID-Reader_ prüft, ob *Pilot* existiert
. IF *Pilot* existiert
.. `Anmeldedaten` werden erfolgreich gespeichert.
.. _Signallämpchen_ leuchtet in Grün auf. 
. ELSE *Pilot* existiert nicht
.. _Signallämpchen_ blinkt Rot auf. 
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe

//Systemausfall -> ist für uns nicht relevant (Aussage vom Verein)  

==== keine Internetverbindung
Wenn sich der *Pilot* im Schritt 3 des Standardablauf erfolgreich anmeldet, und die Daten entgegengenommen werden. In diesem Fall können aber die `Anmeldedaten` noch nicht zu den Webserver synchronisiert werden. 

//Nichtfunktionale Anforderung -> Anmeldedaten müssen lokal vorbehalten werden und werden beim späteren Versuch synchronisiert


==== Systemausfall
Wenn der *Pilot* im Schritt 2 des Standardablauf sich versucht anzumelden, die Anmeldung aus einer anhaltenden technischen Störung fehlschlägt:

. *Pilot* greift zum ursprünglichen manuellen System zurück 
. *Pilot* trägt alle geforderten Daten händisch in das Flugbuch ein 
. *Pilot* muss die technische Störung an *Administrator* weiterleiten
. Der Use Case wird im Schritt 4d fortgesetzt.


=== Wesentliche Szenarios

==== Erfolgreiche Anmeldung
. Sc1: *Pilot* A. trifft am Flugplatz ein. A. hällt seinen _RFID-Ausweis_ an den _RFID-Reader_. Die `Anmeldedaten` werden erfolgreich gespeichert und das _Signallämpchen_ leuchtet in Grün auf. A. darf den Flugplatz betreten.

===	Nachbedingungen

Bei erfolgreicher Durchführung des Use Case müssen folgende Nachbedingungen erfüllt sein:

* _Signallämpchen_: Das _Signallämpchen_ sollte sich bei jeder versuchten Anmeldung (erfolgreich oder nicht erfolgreich):

. davor und danach für eine Sekunde ausshalten. 
. auf ihren korrekten Zustand zurücksetzten.  

//nicht funktionale Anforderungen -> technische Störung -> Admin bescheud geben etc.

=== Besondere Anforderungen

//nicht funktionale Anforderungen ->  Performance ("schnelles" lesen des Readers) & Usability (einfach und verständliches System)


