== Use-Case: UC06: Alle Piloten abmelden
===	Kurzbeschreibung

In diesem Use-Case wird der komplette Vorgang der Abmeldung aller *Vereinsmitglieder* beschrieben.

===	Kurzbeschreibung der Akteure
==== Vereinsmitglieder
Der Akteur Vereinsmitglied möchte sich und alle anderen *Vereinsmitglieder* abmelden und den Flugplatz verlassen.

==== Administrator
Der Akteur Administrator möchte alle *Vereinsmitglieder* auf einmal abmelden.

=== Vorbedingungen
. Die *Vereinsmitglieder* sind angemeldet.

=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, wenn ein *Vereinsmitglied* gehen möchte und alle anderen *Vereinsmitglieder* abmelden möchte.
//sicher?
. Das *Vereinsmitglied* drückt (z.B.) lange auf den _Flugleiterknopf_.
. Alle *Vereinsmitglieder* werden abgemeldet.
//oder wie auch immer es aussehen soll, wenn niemand mehr angemeldet ist
. Die LED hört auf zu leuchten und alle Mitglieder sind abgemeldet.
. Der Vereinsflugplatz kann verlassen werden.
. Der Use-Case ist abgeschlossen.

=== Alternative Abläufe
==== Deadline
Es ist 24:00 Uhr und es sind noch *Mitglieder* angemeldet.

. Alle Mitglieder werden automatisch vom _System_ abgemeldet.
. Die LED hört auf zu leuchten und alle Mitglieder sind abgemeldet.

==== Admin
Der *Administrator* möchte alle *Vereinsmitglieder* abmelden.

. Der *Administrator* klickt auf der _Adminpage_ auf die Schaltfläche _Alle Mitglieder Abmelden_.
. Die LED hört auf zu leuchten und alle Mitglieder sind abgemeldet.

=== Wesentliche Szenarios

==== Erfolgreiche Abmeldung

. Sc1: Alle *Vereinsmitglieder* werden abgemeldet.

===	Nachbedingungen
Das Signallämpchen sollte nicht mehr leuchten und alle *Vereinsmitglieder* sollten abgemeldet sein.


=== Besondere Anforderungen

==== Usability

Der Use Case gehört zu der erweiterten Funktionalität des Systems und muss daher für die meisten Vereinsmitglieder einfach und verständlich sein.