= Vision: {project-name}
Jakob  Laufer  <email@domain.org>; Tsatsralterdene Batchimeg <tsatsralterdene.batchimeg@htw-dresden.de>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten der "Anwesenheitserfassung des Modellflugplatzes" zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie die "Anwesenheitserfassung" diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf "Anwesenheitserfassung für Piloten", das vom Team "E2" entwickelt wird. Das System wird es dem "Vereinsflugplatz des Mfc-Rossendorf" erlauben, die Anwesenheitserfassung zu nutzen, um damit einen sicheren und zuverlässigen Praxisbetrieb des Vereinsflugplatzes zu erreichen. 

->zwang vom Gesetzgeber -- einige Bürokratische Maßnahmen erleichtern

=== Definitionen, Akronyme und Abkürzungen
siehe Glossar (Verweis hier einfügen).

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)

== Positionierung
=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

Im Rahmen einer studentischen Projektarbeit hat uns der "Vereinsflugplatz des Mfc-Rossendorf" die Möglichkeit gegeben, einen aktuellen Vorgang sicher/erweitern etc............

Um einen sicheren Betrieb des Vereinsflugplatzes zu gewährleisten gibt es einige gesetzliche festgelegte bürokratische Maßnahmen zu beachten. 
Eines davon ist die erfassung/protokollierung der anwesenden Piloten/Mitarbeiter. Aktuell findet die erfassung durch ein zentrales Flugbuch von statten, in welches sich Piloten eintragen.  

Um das aktuell notwendige System ........zu- automatisieren/erleichtern/zuverlässiger/komfortabler zu machen........, soll nicht mehr über ein händisches/manuelles eintragen durch ein Flugbuch die Anwesenheit protokoliert werden, sondern lokal über einen RFID-Tag digital erfasst und gesichert werden.  





=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
|Das Problem |	DONNERSTAG klären 
|betrifft |	Piloten bzw. Mitarbeiter des Flugplatzes (vll. Gesetzgeber) 
|die Auswirkung davon ist |	unsicher, unzerflässig ....DONERSTAG
|eine erfolgreiche Lösung wäre |	Ein System für die anwesenheitserfassung bzw. protokollierung der Piloten über einen Raspberry Pi, der die Daten ausliest und verarbeitet.
|===

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
|Für|	Piloten/Mitarbeiter
|die| die den Flugplatz betreten und fliegen wollen.	
|Das Produkt| ??
|welches| den sicheren Betrieb des Flugplatzes gewährleistet
|Im Gegensatz zu| dem aktuellen System (Flugbuch)
|Unser Produkt|	gewährleistet die sichere An/Abmeldung, Verarbeitung, verwaltung und Synchronisation der Daten auf dem Webserver.
|===

==	Stakeholder Beschreibungen
===	Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
|Name|	Beschreibung	| Verantwortlichkeiten
|[Benennung des Stakeholder-Typs.]	|[Kurze Beschreibung des Stakeholders.]	|[Fassen Sie die wesentlichen Verantwortlichkeiten des Stakeholder mit Bezug auf das zu entwickelnde System kurz zusammen, d.h. ihr besonderen Interessen. Beispiele: Dieser Stakeholder sorgt dafür, dass das System gewartet wird / dass die angezeigten Daten aktuell sind / überwacht den Projektfortschritt / usw.]

|Kunde
|Auftraggeber vom  Mfc-Rossendorf
|Einblick in die derzeitige Lage der Anwesenheitserfassung, Ansprechpartner

|Piloten
|Mitglieder des Vereins welche den Flugplatz aktiv nutzen
|für den Flugplatz und dessen sichere Nutung (An/Abmelden, Regeln einhalten et.)

|Mitarbeiter
|Personen die bei dem MFC-Rossendorf angestellt sind und auf dem Flugplatz arbeiten
|geregelten Ablauf auf dem Flugplatz, Ordnung, Erfassung der Daten

|Besucher
|Die Belgleitung von den Piloten oder auch unbeteiligte Zuschauer
|

|Gesetzgeber 
|gibt rechtliche/bürokratische Rahmenbedingungen vor (sicherheit)
|überwacht Gesetze und Regelungen hinsichtlich Sicherheit

|Entwickler 
|arbeiten an Projekt und setzten es um
|analysieren, entwerfen, implementieren und Testen das zu entwickelnde Projekt

|Wartungspersonal
|
|

|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das? -> Anzahl der Nutzer
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Produkt-/Lösungsüberblick
=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.


[%header, cols="4,1,4,1"]
|===
|Bedarf|	Priorität|	Features|	Geplantes Release
|xx|xx|xx|xx
|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
|Anforderung|	Priorität|	Geplantes Release
|xx|xx|xx|
|===
