= Architecture Notebook: {project-name}
Alexander Heiß <alexander.heiß@htw-dresden.de>; Lenny Reitz <lenny.reitz@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!

== Architekturziele und Philosophie
//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).

Das System stellt die Anwesenheitserfassung der Piloten auf dem Flugplatz des Mfc-Rossendorf dar. Dabei gibt es eine physische und funktionale Zweiteilung in An- und Abmeldung am Terminal vor Ort (Flugplatz) auf der einen und Verwaltung des Systems über einen Webserver auf der anderen Seite.

Die vom Terminal erzeugten Protokolldaten werden über den Webserver in eine *Datenbank* gespeichert, welche neben den Flugdaten der Piloten, auch die Piloteninformationen selbst beinhaltet.

Bei der Erfassung der Aktivitäten auf dem Flugplatz steht die exakte zeitliche Einordnung der Ereignisse im Vordergrund. Das erfordert eine *aktuelle Uhrzeit* am Terminal und die Möglichkeit der *Offline-Nutzung*, da nicht immer gewährleistet werden kann, dass eine Verbindung zum Webserver und damit zur Datenbank besteht.

Da das Terminal im Freien steht, wird auf eine *robuste Installation* gesetzt, um Wettereinwirkungen und möglicher physischer Gewalt standzuhalten. Konkret bedeutet das, dass der Raspberry Pi im Boden verbaut wird und die Komponenten zur An- und Abmeldung in einem Kasten eingebettet an einem Mast befestigt sind.

Darüber hinaus soll sich die Anlage möglichst *nahtlos in die Flugaktivitäten der Piloten eingliedern*. Das bedeutet, dass ein möglichst reibungsloser und schneller Ablauf der Prozesse am Terminal gewährleistet sein muss, um die Nutzungsbereitschaft hochzuhalten. Darüber hinaus soll sich das Terminal die meiste Zeit über nicht bemerkbar machen, d.h. solange niemand mit der Anlage interagiert oder Piloten auf dem Platz sind, gibt die Anlage auch kein visuelles Feedback.

Um die oberen Aspekte, insbesondere die der Widerstandsfähigkeit gegenüber Vandalismus, zu erfüllen, wird auf eine *minimalisitische Ausgabe* als Feedback für den Benutzer des Terminals gesetzt (einfache RGB-Leuchte). Da viele der Piloten keine umfangreichen Kentnisse bezüglich der Funktionsweise der Anlage haben, stellt eine einfache und verständliche Lichtrückmeldung eine zentrale Umsetzungsrolle dar. Das selbe gilt auch für die Verwendung des RFID-Scanners und der Benutzung des Flugleiter-Knopfes.

Der Webserver soll durch eine *moderne Oberfläche* eine einfache Übersicht und Verwaltungsoption für die Administratoren bieten und für die Mitglieder eine beschränkte Übersicht über aktuelle Aktivitäten auf dem Flugplatz. Der Zugang für Administratoren und Mitglieder wird seperat *durch Logins gesichert*.

Das System muss *skalierbar* sein, da davon auszugehen ist, dass zusätzlich zur Anwesenheitserfassung der Piloten, in Zukunft auch eine Anwesenheitserfassung in der Werkstatt des Vereins geplant ist.


== Annahmen und Abhängigkeiten
//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

*Annahmen:*

* Es exitsieren ausreichend RFID-Ausweise, sodass sich jeder Pilot am Terminal eindeutig identifizieren kann.
* Die Solarkollektoren am Terminal liefern ausreichend Strom für die dauerhafte Betreibung des Raspberry Pis.

*Abhängigkeiten:*

* Es besteht eine gegenseitige Abhängigkeit zwischen Webserver und Terminal. Beide Teile des Systems müssen miteinander kommunizieren können.

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.

=== Funktional
include::../requirements/system-wide_requirements.adoc[tag=nfaf1]
include::../requirements/system-wide_requirements.adoc[tag=nfaf2]

=== Zuverlässigkeit (Reliability)
include::../requirements/system-wide_requirements.adoc[tag=nfar1]

=== Effizienz (Performance)
include::../requirements/system-wide_requirements.adoc[tag=nfap1]
include::../requirements/system-wide_requirements.adoc[tag=nfap2]

=== Wartbarkeit (Supportability)
include::../requirements/system-wide_requirements.adoc[tag=nfas1]
include::../requirements/system-wide_requirements.adoc[tag=nfas2]
include::../requirements/system-wide_requirements.adoc[tag=nfas3]

=== Zusätzliche Anforderungen
include::../requirements/system-wide_requirements.adoc[tag=nfa+3]
include::../requirements/system-wide_requirements.adoc[tag=nfa+4]



== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

. Wir haben uns entschieden bei der Umsetzung der Webserver-Oberfläche auf das Frameworks Angular und Djano zu setzen, da
.. das Projekt "Wetterstation" diese Frameworks auch verwendet hat
.. in unserer Gruppe keine Erfahrungswerte zu JS-Frameworks bestehen
.. die Themensteller eine moderne Oberflächengestaltung mit JS-Frameworks wünschen

. Bei der Enstscheidung über die Rückmeldevarianten am Terminal haben wir uns gegen ein Display und für eine RGB-LED entschieden, da der Aufwand einer speziellen Nutzeroberfläche und die Auswahl und Einrichtung eines Displays dem relativ kleinen Funktionsumfang des Terminals nicht gerecht wird. Man kann die Rückmeldung aller Ereignisse ebenso gut mit einer RGB-LED realisieren, die unterschiedlich oft und in verschiedenen Farbkombinationen aufblinkt.

. Wir haben uns für eine relationale Datenbank entschieden, da sich unsere Datenobjekte (Piloten, Protokoll) dafür anbieten. Insbesondere für die fortlaufende Protokollierung eignet sich hier eine relationale Datenbank.

. Wir haben beschlossen, die relationale Datenbank auf dem Raspberry Pi (Zwischenspeicher) mit MariaDB umzusetzen, da es hier bereits Erfahrungswerte in der Gruppe gibt.

. Wir haben uns für eine MySQL Datenbank für die Haltung der Daten auf dem Webserver entschieden, da es persönliche Erfahrungswerte gibt und zahlreiche Informationsquellen.

. Für die Kommunikation zwischen Raspberry Pi und Webserver nutzen wir REST API, auf Vorschlag der Themensteller.

. Die Skriptprogrammierung des Raspberry Pi erfolgt mit Python, da es auch hier bereits Erfahrungswerte gibt und eine Skriptsprache von den Themenstellern verlangt wird.

== Architekturmechanismen
https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. Aus NFAF-1 geht hervor, dass Admins und Piloten Anmeldedaten erhalten müssen, um sich auf dem Webserver einzuloggen. Im Gespräch mit den Themenstellern hat sich ergeben, dass es jeweils ein Zugang für die Rollen Administrator und ein Zugang für die Rolle Pilot geben soll. Jeder Pilot loggt sich dann also über den Piloten-Zugang ein mit beschränkter Funktionalität und jeder Admin über den Admin-Zugang mit vollem Funktionsumfang. Die konkrete technische Realisierung dieser getrennten Logins steht noch nicht fest.

. Für die Gestaltung des Frontends des Webservers wird sich ein _Responsive Design_ eignen, da die Webseiten sowohl auf einem Smartphone als auch auf einem Desktop-PC ausgegeben werden. Die Administratoren werden die Verwaltung der Piloten wahrscheinlich hauptsächlich am Desktop-PC durchführen, während die Piloten den Status am Flugplatz auch mal vom Smartphone aus verfolgen wollen.

. Wie aus NFAF-3 und NFAR-1 hervorgeht, muss der Raspberry Pi bei bestehender Internetverbindung in gewissen zeitlichen Abständen auf externe Informationen zugreifen. Dabei handelt es sich einerseits um eine triviale Aktualisierung der Uhrzeit des Raspis. Andererseits müssen Piloten- und Protokolldaten mit dem Webserver ausgetauscht bzw. synchronisiert werden. Zu synchronsierende Daten fallen auf beiden Seiten an, Terminal und Webserver. Zum einen kann über den Webserver ein neuer Pilot hinzugefügt werden, der dem Terminal erst bekannt gemacht werden muss. Auf der anderen Seite müssen die zunächst lokal gehaltenen Protokolländerungen am Terminal auch den Webserver erreichen. Bei Absprache mit den Themenstellern hat sich herausgestellt, dass dabei eine zeitgesteuerte Synchronisation wünschenswert ist. Die genaue technische Umsetzung der Kommunikation streben wir über REST API an, die logischen Feinheiten der Synchronisierung stehen noch nicht fest.

. Durch NFA+-3 und den vorherigen Absatz lässt sich schlussfolgern, dass, wenn es eine zeitgesteuerte Synchronisation gibt, diese in relativ langen Zeitabständen (30 min) stattfindet. Noch auszuschließen ist, ob es sich wirklich ausschließlich um eine rein zeitgesteurte Synchronnisation handeln soll. Es gäbe dann also keinen Befehl vom Webserver, der sofort am Terminal umgesetzt werden würde.

. Für den Testbetrieb in der Praxis ist es sinnvoll, die einzelnen Parameter für die Befehle am Terminal nicht festzuschreiben. Im Vordergrund steht hier vor allem die Zeitdauer die für ein An- bzw. Abmeldung angesetzt wird (3s) und die Zeitdauer für die Abmeldung aller Piloten (10s). Diese Parameter sollen durch den Administrator konfigurierbar sein (NFAP-1 und NFAS-3), um Erfahrungswerte aus der Praxis leicht einstellen zu können. Es steht noch aus, ob die Konfiguration sich ausschließlich um die Zeitdauern dreht, oder ob auch weitere Parameter (LED-Farbe, LED-Blink-Rhythmus, Befehlsreihenfolge) konfigurierbar sein sollen.

. Das Anlernen neuer RFID-Ausweise zum System ist bisher noch nicht technisch spezifiert. Wir gehen jedoch von beschreibbaren RFID-Ausweisen aus, die über einen einfachen Code identifiziert und auch händisch in das System eingetragen werden können. 

. Ein weiterer technisch unbekannter Aspekt ist die genaue Anfrage des Terminals an den Webserver, um die Datenstände zu synchronisieren. Hier handelt es sich nicht um eine Anfrage in Form einer Webseite, sondern über eine Anfrage, die im Hintergrund abgehandelt werden soll.


////

== Wesentliche Abstraktionen
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]

== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]

////

== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten von Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.

=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante Anforderungen enthalten.

