= Iteration Plan 01: E2 Anwesenheitserfassung Modellflugplatz
Tsatsralterdene Batchimeg <tsatsralterdene.batchimeg@htw-dresden.de>; Max Haufe <max.haufe@htw-dresden.de>; Alexander Heiß <alexander.heiss@htw-dresden.de>; Simon Herbstrith <simon.herbstrith@htw-dresden.de>; Richard Kleint <richard.kleint@htw-dresden.de>; Jakob Laufer <jakob.laufer@htw-dresden.de>; Lenny Reitz <lenny.reitz@htw-dresden.de>; Dirk Zimmermann <dirk.zimmermann@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Meilensteine
//Meilensteine zeigen den Ablauf der Iteration, wie z.B. den Beginn und das Ende, Zwischen-Meilensteine, Synchronisation mit anderen Teams, Demos usw.

[%header, cols="3,1"]
|===
| Meilenstein
| Datum

| Beginn der Iteration | KW 1
| Ende der Iteration | KW 2
|===


== Wesentliche Ziele
//Nennen Sie 1-5 wesentliche Ziele für die Iteration.

* Erstellung Wireframes
* Use-Case-Diagramm und Use Cases weiterentwickeln
* System-Wide-Requirements bearbeiten
* Bedienungs- & Zustandsplan des Terminals vor Ort erstellen

== Aufgabenzuordnung
//Dieser Abschnitt sollte einen Verweis auf die Work Items List enthalten, die die für diese Iteration vorgesehenen Aufgaben dokumentiert sowie die Zuordnung dieser Aufgaben zu Teammitgliedern. Alternativ können die Aufgaben für die Iteration und die Zuordnung zu Teammitgliedern in nachfolgender Tabelle dokumentiert werden - je nach dem, was einfacher für die Projektbeteiligten einfacher zu finden ist.

Die in dieser Iteration geplanten Aufgaben sind in vereinfachter Form in der Work Items List auf GitHub dargestellt: https://github.com/simonherbstrith/E2-Anwesenheitserfassung-fuer-Modellflugplatz/projects/1.

Hinweise zur Darstellung:

* Priorität 1 = hoch
* Priorität zeigt vor allem zeitliche Reihenfolge
* WIDs mit Priorität n! müssen zwingend innerhalb der Iteration fertiggestellt werden
* AM ... Allgemeines Meeting mit Themensteller

Diese Aufgaben werden in dieser Iteration bearbeitet:
[%header, cols="1,3,1,1,1,2,1,1,1,1"]
|===
|WID
| Aufgabe bzw. Beschreibung | Priorität |Schätzung der Größe (Punkte) |Status | Referenzen |geplante Iteration | Zugewiesen (Name) | Gearbeite Stunden | Schätzung der verbleibenden Stunden


| 1 | Wireframes erstellen | 2 | 24 | 90% | x | 3-4 | Alex | 9 | 2 | 

2 | Weiterentwicklung Use-Cases | 7 | 120 | 100% | x | 2-3 | Analyse (+Hilfe Entwurf) | 22 | 0 |

3 | Erstellung Test-Cases | 3 | 6 | 40% | x | 3-4 | Alex | 4 | 1 |

4 | Glossar weiterentwickeln | 1 | 2 | 100% | x | 1-3 | Analyse | 3 | 0 |

5 | Weiterentwicklung Risikoanalyse | 6 | 2 | 80% | x | 1-4 | Analyse (Rest) | 8 | 0 |

6 | Systemkonzept erstellen (C4) | 9 | 6 | 100% | x | 3 | Entwurf | 20 | 15 |

7 | Bearbeitung Risikoanalyse | 11 | 24 | 80% | x | 1-4 | Analyse, Simon | 9 | 4 |

8 | Zusammenstellung Wireframes, Use-Cases für AM | 13! | 2 | 100% | x | 1 | Analyse, Entwurf, Alex | 3 | 0 |

9 | System-Wide-Requirementes erstellen | 8 | 2-4 | 30% | x | 1 | Analyse, Entwurf | 4 | 14 |

10 | Bearbeitung Architecture Notebook | 4 | 24 | 40% | x | 3-4 | Entwurf | 4 | 7 |

11 | Bedienungsplan für Terminal erstellen | 5 | 6 | 100% | x | 1-2 | Lenny, Alex | 5 | 0 |

12 | Use-Case-Diagramm (vorläufig) finalisieren | 10 | 6 | 100% | x | 3 | Jakob | 3 | 0 |
|===

*Aufgaben Team-TS-Meeting:*

* Use-Case-Diagramm Vorstellung
* Use-Cases-Vorstellen
* Aufgetretene Fragen stellen
* Bedienungsplan vorstellen

== Aufgetretene Probleme
//Optional: Führen Sie alle Probleme auf, die in dieser Iteration adressiert werden sollen. Aktualisieren Sie den Status, wenn neue Probleme bei den täglichen / regelmäßigen Abstimmungen berichtet werden.
* Es wurden zu viele UseCases zu detailliert beschrieben. Auch müssen nicht Software-relevante Elemente entfernt werden
* Die Bedienung des Terminals wurde zu kompliziert geplant. Für die Akzeptanz der Nutzer müssen einige Prozesse, trotz erhöhter Fehleranfälligkeit, vereinfacht werden.
* Das AM wurde zu ausführlich und lang gestaltet. Im nächsten AM müssen die Themengebiete eingeschränkt werden


//[%header, cols="2,1,3"]
//|===
//| Problem | Status | Notizen
//| x | x | x
//|===


== Bewertungskriterien
//Eine kurze Beschreibung, wie Erfüllung die o.g. Ziele bewertet werden sollen.
* Alle Work Items mit ! erreicht
* Dem Themensteller angekündigte Änderungen/Ziele erfüllt und präsentiert
* Fragen dokumentiert & Antwort erhalten
* Mindestens 90% der Work Items für die aktuelle Iteration mit mindestens 80% Vollständigkeit (außer die planmäßig in nächste Iteration zu übertragende Work Items)

//* 97% der Testfälle auf Systemebene sind erfolgreich.
//* Gemeinsame Inspektion des Iterations-Ergebnisses (Inkrement) mit den Abteilungen X und Y ergibt positive Rückmeldung.
//* Technische Präsentation / Demo erhält positive Rückmeldungen.


== Assessment
//In diesem Abschnitt werden die Ergebnisse und Maßnahmen der Bewertung erfasst und kommunziert. Die Bewertung wird üblicherweise am Ende jeder Iteration durchgeführt. Wenn Sie diese Bewertungen nicht machen, ist das Team möglicherweise nicht in der Lage, die eigene Arbeitsweise ("Way of Working") zu verbessern.

=== Kundengespräch

[%header, cols="1,3"]
|===
| Assessment Ziel | Iteration 1
| Assessment Datum | 03.12.2020
| Teilnehmer | Analyse, Leiter, TS
| Projektstatus	| Grün-Gelb (siehe Probleme)
|===



=== Teammeeting

[%header, cols="1,3"]
|===
| Assessment Ziel | Iteration 1
| Assessment Datum | 09.12.2020
| Teilnehmer | Gesamtes Team
| Projektstatus	| Grün-Gelb (siehe Probleme)
|===

*Beurteilung im Vergleich zu den Zielen*

Die Wireframes wurden vollständig erstellt und wurden vom TS bis auf Kleinigkeiten akzeptiert. Die Use-Cases sowie der Bedienungsplan müssen gemäß der Problembeschreibung erneut bearbeteitet werden. Die System-Wide-Requirements soweit in Ordnung und werden in die nächste Iteration übernommen.

*Geplante vs. erledigte Aufgaben*

Es wurden alle Bewertungskriterien erfüllt. Einige Aufgaben müssen zur Nachbesserung in die nächste Iteration übernommen werden.

//* Andere Belange und Abweichungen
//Führen Sie weitere Themen auf, für die eine Bewertung durchgeführt wurde. Beispiele sind Finanzen, Zeitabweichungen oder Feedback von Stakeholdern, die nicht bereits an anderer Stelle dokumentiert wurden.
