// --- 1. Projektthema -------------------------
= Testdokumentation
// --- 2. Teammitglieder -----------------------
Jakob Laufer <jakob.laufer@htw-dresden.de>; Alexander Heiß <alexander.heiß@htw-dresden.de>;
// --- 3. Abgabedatum --------------------------
04. Juli 2021
// ---------------------------------------------
:docs: ../../docs
include::{docs}/_includes/default-attributes.inc.adoc[]

:doctype: book
:toc:
:toclevels: 1
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-label:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
// Folders
:imagesdir-reset: {imagesdir}
:docs-test: {docs}/test
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development


== Testkonzept

=== Testobjekte

Die Grundlage unserer Tests bilden die Use-Case-orientierten Testfälle. Das bedeutet, dass zu den primären zehn Use-Cases zahlreiche Testfälle aufgelistet und bearbeitet wurden. Ergänzt werden diese durch UseCase-übergreifende Tests, die beispielsweise die Einstellungen der Website betreffen.

Der Fokus des Testing lag gleichmäßig verteilt auf den Websitekomponenten, den Terminalfunktionalitäten und der Synchronisation zwischen diesen. Eine Auflistung der Komponenten ist in den jeweiligen TestCases zu finden.

=== Testmethoden

Als grundlegende Prüftechnik wurde der dynamische Test umgesetzt. Somit wurden die lauffähigen Software-Bestandteile nacheinander getestet. Es fanden sowohl Positiv- als auch Negativtests zur Überprüfung der korrekten Funktionalität statt.

Als Test-Praktik wurde Concurrent Testing verwendet. So wurden bereits Teilergebnisse der Komponenten getestet und den Entwicklern zu einem frühen Zeitpunkt Feedback gegeben.

==== Modultests

Es wurde sich im Team ausführlich über die Verwendung von Modultests ausgetauscht und nach einiger Überlegung gegen die umfassende Verwendung dieser entschieden. Dies hat als Begründung, dass unser System kaum Komplexität in einem einzelnen Modul selbst besitzt, sondern durch die Verbindung zu anderen Modulen an dieser gewinnt. Einzelne Modultests, wie zum Beispiel die Überprüfung des Textes in Eingabemasken (Überprüfung innerhalb des Moduls), sowie Responsive-Tests wurden durchgeführt.

==== Integrationstest

In unserem Testvorgang stand insbesondere der Integrationstest im Vordergrund. So wurde orientiert an den Use-Cases die Integration vieler Module überprüft und deren Synchronisation kontrolliert. Zahlreiche Integrationstest sind in den nachfolgenden TestCases aufgeführt.

==== Systemtest

Der Systemtest fand aufgrund der späten Hardware-Lieferung erst wenige Tage vor dem Deployment statt. Dort wurde insbesondere die erfolgreiche Synchronisation zwischen Webserver und Terminal überprüft und das System als Gesamtheit getestet.

=== Akzeptanztest

Dem Kunden wurden iterativ die einzelnen Systemteile zur Abnahme vorgestellt und vor dem Deployment das Gesamtsystem vorgestellt. Aufgrund der Hardware-Komponente mussten wir diesen Teil verbal erklären. Die Themensteller konnte ca. zwei Wochen vor dem Deployment selbstständig die Website bedienen und die Funktionen ausprobieren. Das Feedback erhielten wir zügig und konnten das System erfolgreich validieren. Des Weiteren wurden die nicht-funktionalen Anforderungen sowie alle Softwarebestandteile während des Deployments durch die Themensteller abgenommen.
                          
=== Testdurchführungsplanung 

Zuständig für die Tests ist gemäß Projektplan Alexander Heiß.

Unterstützt wurde Alexander Heiß bei der Erstellung der allgemeinen TestCases durch Max Haufe, ab Iteration 8 übernahm Jakob Laufer die Mitarbeit.

Beginnend ab Iteration 3 bis zur Iteration 7 wurden allgemeine TestCases erstellt. Diese waren nicht spezifisch an den Use-Cases ausgerichtet, sondern deckten allgemeine Testfälle des Systems ab. Diese TestCases wurden zu einem späteren Zeitpunkt in die UseCase-spezifischen TestCases eingebunden.

Die Erstellung der TestCases für die UseCases begann in Iteration 8. Bis zur Iteration 10 wurden diese erweitert, getestet und den Entwicklern entsprechendes Feedback gegeben.

Die Durchführung des Systemtests und des Akzeptanztests wurde in den jeweiligen Kapiteln oben beschrieben.


== Interner Test der nicht-funktionalen Anforderungen

===  Systemweite Anforderungen
[cols="4,1,5"]
|===
|Anforderung | erfüllt | Anmerkung

|NFAF-1: Zugriffsschutz (Einsicht des Flugprotokolls nur für Admins und Piloten)
|Ja
|/

|NFAF-2: Datensynchronisierung (ereignisgesteuert)
|Ja
|/

|NFAF-3: Überwachung der Synchronisation (Admin kann einsehen, wann das Flugprotokoll zuletzt synchronisiert wurde)
|Nein
|Noch nicht implementiert

|NFAU-1: Aufgabeneffizienz (Simple und intuitive Kombinationen am Terminal)
|Ja
|/

|NFAU-2: Intuitives Bedienen (Bedeutung der Statusmeldungen der LED erkennbar)
|Nein
|Keine LED vorhanden

|NFAU-3: Benutzerfreundlichkeit (Responsive Webdesign)
|Ja
|/


|NFAP-1: Antwortzeiten (Konfigurierbare Antwortzeiten durch Admins)
|Ja
|/

|NFAP-2: Durchsatz (Piloten können sich hintereinander (innerhalb von 30 Sekunden) an- und abmelden)
|Ja
|/

|===

[.landscape]
<<<

== Testfallbeschreibung & Testergebnisse

include::{docs-test}/test_cases_UC01_Pilot_anmelden.adoc[]
<<<
include::{docs-test}/test_cases_UC02_Pilot_abmelden.adoc[]
<<<
include::{docs-test}/test_cases_UC03_Pilotendaten_anlegen.adoc[]
<<<
include::{docs-test}/test_cases_UC04_Pilot_deaktivieren.adoc[]
<<<
include::{docs-test}/test_cases_UC05_Pilotendaten_modifizieren.adoc[]
<<<
include::{docs-test}/test_cases_UC06_Alle_Piloten_abmelden.adoc[]
<<<
include::{docs-test}/test_cases_UC07_Flugleiter_bestimmen.adoc[]
<<<
include::{docs-test}/test_cases_UC08_Protokoll_einsehen.adoc[]
<<<
include::{docs-test}/test_cases_UC09_Protokolldaten_nachträglich_einfügen.adoc[]
<<<
include::{docs-test}/test_cases_UC10_Handhabung_Gastflüge.adoc[]
<<<
include::{docs-test}/test_cases_UC11_Pilot_reaktivieren.adoc[]
<<<

include::{docs-test}/test_cases_configurations.adoc[]
<<<


=== Abnahmetest

Der Abnahmetest ist im Abnahmeprotokoll aufgeführt.